### ISSUE TITLE
error when run npm start on Windows

### ISSUE THREAD

**Issue by almoulki** [webauthn-open-source/fido2-server-demo#26]
Hello,
 errror when i run command "npm start"
how i can solve them?
thank you

ERROR: TypeError: process.getuid is not a function
    at path_to_lib\fido2-server-demo\node_modules\simple-component-manager\lib\component-director.js:206:25
    at new Promise (<anonymous>)
    at ComponentDirector.installComponents ( path_to_lib\fido2-server-demo\node_modules\simple-component-manager\lib\component-director.js:187:16)
    at Function.start ( path_to_lib\fido2-server-demo\node_modules\simple-component-manager\lib\component-director.js:49:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15180) UnhandledPromiseRejectionWarning: TypeError: process.getuid is not a function
    at path_to_lib\fido2-server-demo\node_modules\simple-component-manager\lib\component-director.js:206:25
    at new Promise (<anonymous>)
    at ComponentDirector.installComponents ( path_to_lib\fido2-server-demo\node_modules\simple-component-manager\lib\component-director.js:187:16)
    at Function.start ( path_to_lib\fido2-server-demo\node_modules\simple-component-manager\lib\component-director.js:49:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by miloskuchar** [comment]
I have a same problem. Please anz fix available?
